Confirmed registration pug template
wearethefuture-org/shop-auction-front pull request #115
Opened 2021-05-10 16:36 UTC by Movchan94

2021-05-10 16:37 UTC, Movchan94 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Підтвердження акаунта через gmail](https://trello.com/c/piR3J5V3/116-%D0%BF%D1%96%D0%B4%D1%82%D0%B2%D0%B5%D1%80%D0%B4%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-%D0%B0%D0%BA%D0%B0%D1%83%D0%BD%D1%82%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-gmail)

2021-05-17 11:35 UTC, ArtemBozhok requested changes

2021-05-17 11:35 UTC, ArtemBozhok commented on components/account/verifyAccount/verifyAccount.tsx
> +    }, [codeQuery],
для чого в залежності квері? У тебе цей фетч повинен запускатись один раз після завантаження компонента.

2021-05-17 11:35 UTC, ArtemBozhok commented on components/account/verifyAccount/verifyAccount.tsx
> + // const { setMounted } = useMounted();
видали комент

2021-05-17 11:35 UTC, ArtemBozhok commented on components/modals/auth/ConfirmedUserModal.tsx
> +          Вітаємо з успішною реєстраціїєю!!!
h1

2021-05-17 11:35 UTC, ArtemBozhok commented on components/modals/auth/ConfirmedUserModal.tsx
> +          <br />Для завершення реєстрації необхідно підтвердити Ваш email.
<p> і без br

2021-05-24 08:56 UTC, ArtemBozhok approved these changes

2021-05-24 08:57 UTC, merged