TASK-103 make My Reviews a working section
wearethefuture-org/shop-auction-front pull request #119
Opened 2021-05-14 11:51 UTC by maxim-zabolotny

2021-05-14 11:51 UTC, maxim-zabolotny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Зробити робочим розділ "Мої відгуки"](https://trello.com/c/GnQTQUQ6/103-%D0%B7%D1%80%D0%BE%D0%B1%D0%B8%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%87%D0%B8%D0%BC-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB-%D0%BC%D0%BE%D1%97-%D0%B2%D1%96%D0%B4%D0%B3%D1%83%D0%BA%D0%B8)

2021-05-17 12:21 UTC, ArtemBozhok requested changes
https://take.ms/djsHA - після того, як змінюєш комент лінк на товар ламається
https://take.ms/7NbRJ - так виглядає комент на наступній сторінці

2021-05-17 12:21 UTC, ArtemBozhok commented on components/account/comments/userCommentItem.tsx
> +import Avatar from 'react-avatar';
перенос рядка

2021-05-17 12:21 UTC, ArtemBozhok commented on components/account/comments/userCommentItem.tsx
> +import { RiChatSettingsLine } from 'react-icons/ri';
розділяй свої імпорти і імпорти бібліотек

2021-05-17 12:21 UTC, ArtemBozhok commented on components/account/comments/userCommentItem.tsx
> +  getFormValue: (c: string) => void;
дай нормальну назву параметру

2021-05-17 12:21 UTC, ArtemBozhok commented on components/account/comments/userCommentItem.tsx
> +  console.log(product);
видали

2021-05-17 12:21 UTC, ArtemBozhok commented on components/account/comments/userCommentItem.tsx
> +  };
розділяй переносами рядків схожі блоки коду

2021-05-17 12:21 UTC, ArtemBozhok commented on hooks/useComments.ts
> +export const useUserComments = (userId: number, page: number, initialData?: ICommentResponse) => {
не потрібна тут initialData
на цій сторінці не потрібен сервер сайд рендер

2021-05-17 12:21 UTC, ArtemBozhok commented on hooks/useComments.ts
> +    },
для чого цей хук, я не бачу щоб ти його десь використовував.

2021-05-17 12:21 UTC, ArtemBozhok commented on interfaces/comment/comment.ts
> +  product: any
продукт це точно не any
і для чого мутейт передавати? Хук на то і хук, щоб виклакити йог оу тому компоненті де його необхідно заюзати.
Повертай із хука mutate де тобі треба і не прокидуй йог опо дереву.

2021-05-17 12:21 UTC, ArtemBozhok commented on interfaces/product/products.ts
> -  avgRating: string;
поверни назад

2021-05-17 12:21 UTC, ArtemBozhok commented on interfaces/product/products.ts
> +  updatedAt: string;
для цього в проекті є інтерфейс BaseEntity від яког опотрібно успадковуватись

2021-05-24 09:09 UTC, ArtemBozhok approved these changes

2021-05-24 09:09 UTC, merged