TASK-118 Fix the filter by price
wearethefuture-org/shop-auction-front pull request #121
Opened 2021-05-15 21:10 UTC by maxim-zabolotny

2021-05-15 21:11 UTC, maxim-zabolotny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Фікс фільтра по ціні](https://trello.com/c/RkhIrujF/118-%D1%84%D1%96%D0%BA%D1%81-%D1%84%D1%96%D0%BB%D1%8C%D1%82%D1%80%D0%B0-%D0%BF%D0%BE-%D1%86%D1%96%D0%BD%D1%96)

2021-05-17 12:26 UTC, ArtemBozhok commented
https://take.ms/Ut1nE - давай тоді і ползунок макс ціни подвинемо лівіше, щоб було симетрично.

2021-05-17 12:27 UTC, ArtemBozhok requested changes
https://take.ms/Ut1nE - давай тоді і ползунок макс ціни подвинемо лівіше, щоб було симетрично.

2021-05-20 14:04 UTC, ArtemBozhok approved these changes

2021-05-20 14:04 UTC, merged