Task 107 add reset password
wearethefuture-org/shop-auction-front pull request #122
Opened 2021-05-16 19:53 UTC by Kovalova22

2021-05-16 19:54 UTC, Kovalova22 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Встановлення і відновлення паролю (виконати після таски про зміну паролю)](https://trello.com/c/j1DP06ee/107-%D0%B2%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D1%96-%D0%B2%D1%96%D0%B4%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8E-%D0%B2%D0%B8%D0%BA%D0%BE%D0%BD%D0%B0%D1%82%D0%B8-%D0%BF%D1%96%D1%81%D0%BB%D1%8F-%D1%82%D0%B0%D1%81%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE-%D0%B7%D0%BC%D1%96%D0%BD%D1%83-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8E)

2021-05-16 19:54 UTC, Kovalova22 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Встановлення і відновлення паролю (виконати після таски про зміну паролю)](https://trello.com/c/j1DP06ee/107-%D0%B2%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D1%96-%D0%B2%D1%96%D0%B4%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8E-%D0%B2%D0%B8%D0%BA%D0%BE%D0%BD%D0%B0%D1%82%D0%B8-%D0%BF%D1%96%D1%81%D0%BB%D1%8F-%D1%82%D0%B0%D1%81%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE-%D0%B7%D0%BC%D1%96%D0%BD%D1%83-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8E)

2021-05-17 12:57 UTC, ArtemBozhok requested changes

2021-05-17 12:57 UTC, ArtemBozhok commented on components/account/personal-info/create-password/create-password.tsx
> +    }
переаір ще раз цей блок, є підозра, що помилка не буе відпрацьвувати. Я на минулому тижні переробив логіку instanse, щоб можна було нормально ловити помилки. Подивись приклад у ПР Саші на методах логіну.

2021-05-17 12:57 UTC, ArtemBozhok commented on components/forms/auth/forgot-password.tsx
> +      } catch (error) {}
аналогічне питання. Пустий блок кетч також не треба залишати, потрібно прокидувати помилку одразу із респонса

2021-05-20 14:02 UTC, ArtemBozhok approved these changes

2021-05-20 14:02 UTC, merged