Task 105-Change email
wearethefuture-org/shop-auction-front pull request #123
Opened 2021-05-19 12:53 UTC by maxim-zabolotny

2021-05-19 12:54 UTC, maxim-zabolotny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реалізувати можливість зміни email](https://trello.com/c/oEnpBYe0/105-%D1%80%D0%B5%D0%B0%D0%BB%D1%96%D0%B7%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D0%BC%D0%BE%D0%B6%D0%BB%D0%B8%D0%B2%D1%96%D1%81%D1%82%D1%8C-%D0%B7%D0%BC%D1%96%D0%BD%D0%B8-email)

2021-05-24 10:45 UTC, ArtemBozhok requested changes

2021-05-24 10:45 UTC, ArtemBozhok commented on api/index.ts
> +    loginAfterChangeEmail: (email: string) => FetchDataType<IAuthResponse>;
Для того, щоб авторизувати юзера цей запит не потрібен. Після успішного підтвердження пошти тобі має прилитіти у респонсі токен і юезр і ти одразу його сетаєш.

2021-05-24 10:45 UTC, ArtemBozhok commented on api/index.ts
> +    changeEmail: (data: IChangeEmail) => FetchDataType<IAuthResponse>;
для зміни імейлу потрібен 1 запит.

2021-05-24 10:45 UTC, ArtemBozhok commented on components/account/personal-info/change-email/change-email.tsx
> +      }
пустий блок кетч
ти помилку тут ніяк не обробляєш
є приклад з авторизацією

2021-05-24 10:45 UTC, ArtemBozhok commented on components/account/personal-info/change-email/confirm-change-email.tsx
> +      }
потрібно показати текст помилки, а не зробити редірект на головну. Юзер нічого не зрозуміє

2021-06-03 10:09 UTC, ArtemBozhok approved these changes

2021-06-03 10:10 UTC, merged