Task 132 fast order front
wearethefuture-org/shop-auction-front pull request #149
Opened 2021-06-01 18:07 UTC by Movchan94

2021-06-01 18:08 UTC, Movchan94 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Швидкий ордер](https://trello.com/c/vaZZwqGc/132-%D1%88%D0%B2%D0%B8%D0%B4%D0%BA%D0%B8%D0%B9-%D0%BE%D1%80%D0%B4%D0%B5%D1%80)

2021-06-02 14:02 UTC, ArtemBozhok requested changes

2021-06-02 14:02 UTC, ArtemBozhok commented on components/forms/auth/fast-order.tsx
> +        });
async await.
кетч ерора не спрацює, приклда дивись у login.tsx, ми ж це обговорювали.

2021-06-03 10:45 UTC, ArtemBozhok approved these changes

2021-06-03 10:45 UTC, merged