79-footer-fix/Fixed footer layout
wearethefuture-org/shop-auction-front pull request #151
Opened 2021-06-02 16:54 UTC by pinokio221

2021-06-02 16:57 UTC, pinokio221 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix footer](https://trello.com/c/AhHsvOC7/79-fix-footer)

2021-06-03 10:37 UTC, ArtemBozhok requested changes
Пк версія - https://take.ms/ITHxy
Мобільна версія - https://take.ms/7M4sA

2021-06-03 10:37 UTC, ArtemBozhok commented on components/Footer/BottomFooter/BottomFooter.module.scss
>      @media screen and (max-width: 1024px) {
у нас є константи styles/vars.scss там є ци брейкпоінти, потрібно їх юзати
додай один рядок відступу

2021-06-03 10:37 UTC, ArtemBozhok commented on components/Footer/Footer.module.scss
> +      @media screen and (max-width: #{$lg}px) {
кожна нова вложенність повинна стартувати з переноса рядка

2021-06-04 10:55 UTC, ArtemBozhok requested changes
Мобільна версія ок.
З Пк проблеми, ширина контейнера менша ніж ширина інших контейнерів сайту, це показно на скріні.
Стилі вирівнювання блоку з соц мережами не правифльні, блок має прижиматись максимально в ліву частину.
Так це має бути https://take.ms/G6vx3
А так це зараз https://take.ms/0Z2rW

2021-06-07 12:28 UTC, ArtemBozhok approved these changes

2021-06-07 12:28 UTC, merged