mobile adaptive
wearethefuture-org/shop-auction-front pull request #47
Opened 2021-03-05 15:00 UTC by astleyz

2021-03-08 12:08 UTC, ArtemBozhok requested changes

2021-03-08 12:08 UTC, ArtemBozhok commented on components/modals/contact-us/ContactUs.tsx
> +import { useTouchDrag } from 'hooks/useTouchDrag';
навіщо це було робити? Хто рухає модальні вікна і для чого? Воно на то і модальне вікно, щоб заблокувати весь контент поки іде взаємодія із ним. Тим більше, що воно не працює.

2021-03-08 12:08 UTC, ArtemBozhok commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.14",
не потрібно нам це.

2021-03-14 20:13 UTC, Maxe1 approved these changes

2021-03-15 20:43 UTC, merged