change favicon
wearethefuture-org/shop-auction-front pull request #65
Opened 2021-04-03 07:38 UTC by ShockVeiw

2021-04-12 15:00 UTC, ArtemBozhok requested changes

2021-04-13 07:06 UTC, ShockVeiw commented on components/layout/MainLayout.tsx
> +        <link rel="manifest" href="/site.webmanifest"/>
туда перенести весь мой добавленный код или только то, что касается фав-иконки?

2021-04-13 12:37 UTC, ArtemBozhok commented on components/layout/MainLayout.tsx
> +        <link rel="manifest" href="/site.webmanifest"/>
все, що стосується іконки

2021-04-14 10:14 UTC, ArtemBozhok approved these changes

2021-04-14 10:14 UTC, merged