TASK-52 add-social-login
wearethefuture-org/shop-auction-front pull request #72
Opened 2021-04-12 14:29 UTC by Kovalova22

2021-04-12 14:36 UTC, Kovalova22 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Логін і реєстрація](https://trello.com/c/vygKO6hn/52-%D0%BB%D0%BE%D0%B3%D1%96%D0%BD-%D1%96-%D1%80%D0%B5%D1%94%D1%81%D1%82%D1%80%D0%B0%D1%86%D1%96%D1%8F)

2021-04-12 16:01 UTC, ArtemBozhok requested changes

2021-04-15 13:51 UTC, ArtemBozhok requested changes

2021-04-15 13:51 UTC, ArtemBozhok commented on .env.example
> +FACEBOOK_APP_ID=143293964389622
якщо необхідно мати доступ дл цих змінних у будь-якому компоненті то перед назвою треба ставити:
NEXT_PUBLIC_REACT_APP_

2021-04-15 15:23 UTC, ArtemBozhok approved these changes

2021-04-15 15:23 UTC, merged