Filters in mobile sidebar
wearethefuture-org/shop-auction-front pull request #85
Opened 2021-04-17 13:00 UTC by Movchan94

2021-04-17 13:02 UTC, Movchan94 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Додати фільтри у мобільне меню](https://trello.com/c/2Xmg8jco/76-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-%D1%84%D1%96%D0%BB%D1%8C%D1%82%D1%80%D0%B8-%D1%83-%D0%BC%D0%BE%D0%B1%D1%96%D0%BB%D1%8C%D0%BD%D0%B5-%D0%BC%D0%B5%D0%BD%D1%8E)

2021-04-19 12:46 UTC, ArtemBozhok requested changes

2021-04-19 12:46 UTC, ArtemBozhok commented on pages/[category]/index.tsx
> -              </div>
поверни як було

2021-04-19 12:59 UTC, ArtemBozhok approved these changes

2021-04-19 13:00 UTC, merged