Task 86 view card product
wearethefuture-org/shop-auction-front pull request #88
Opened 2021-04-19 12:18 UTC by kharkov-timur

2021-04-19 12:18 UTC, kharkov-timur commented
![](https://github.trello.services/images/mini-trello-icon.png) [Відображення карточки товару](https://trello.com/c/jFkO5O64/86-%D0%B2%D1%96%D0%B4%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D1%83)

2021-04-19 14:35 UTC, ArtemBozhok commented
- потрібно прижати цей блок в низ карточки https://take.ms/U59dI
або краще одразу під назвою товару
- коли встановлено рейтинг товару, при наведенні на 1 зірочку немає усі 5 зірочок активні https://take.ms/8NSqM
- лінк на відгуки потрібно зробити робочим на конкретну сторінку
- кількість відгуків також уже приходить із беку

2021-04-19 14:54 UTC, ArtemBozhok requested changes

2021-04-19 14:54 UTC, ArtemBozhok commented on components/catalog-settings/CatalogSettings.module.scss
> -      padding-left: 5px;
навіщо робити роботу яка ніяк не виплаває на результат? 
більше того цей запис
padding: 0 0 0 5px; - абсолютно не читабельний. По вище мені ясно сходу, що це падінг зліва.
а по товєму, мені потрібно сидіти і прикдиувати де топ де лефт де боттом.

2021-04-19 14:54 UTC, ArtemBozhok commented on components/modals/cart/products-in-cart-item/product-in-cart-item.tsx
> +                <a>{name}</a>
не потрібні тут 2 ссилки

2021-04-19 14:54 UTC, ArtemBozhok commented on components/modals/cart/products-in-cart-item/product-in-cart-item.tsx
> +              <Link href={'/views'}>32 відгуки</Link>
зробити лінк на сторінку відгуків і вивести їх реальну кількість

2021-04-19 14:54 UTC, ArtemBozhok commented on components/modals/cart/products-in-cart-item/product-in-cart-item.tsx
>            <div className={style.ProductInCartItem__PlusItemMinusItemQuantity}>
ProductInCartItem__PlusItemMinusItemQuantit - що це за страшна назва класу
до того ж юзати треба camelCase

2021-04-19 14:54 UTC, ArtemBozhok commented on components/modals/cart/products-in-cart-item/product-in-cart-item.tsx
> +              <div className={style.ProductInCartItem__Minus}>
Minus з великої
нижче ProductInCartItem__quantity - з маленької

2021-04-19 14:54 UTC, ArtemBozhok commented on components/products/product-item/product-item.tsx
> +  // let isLiked = true;
видали це, якщо воно білье не потрібно

2021-04-19 14:54 UTC, ArtemBozhok commented on components/star-rating/star-rating.tsx
> +  const [hoverRating, setHoverRating] = useState(0);
повинен бути один стейт а не 2

2021-04-19 14:54 UTC, ArtemBozhok commented on components/star-rating/star.tsx
> +  onMouseEnter: Function;
це не фанкшн а івент хендлер

2021-04-20 09:50 UTC, kharkov-timur commented
![](https://github.trello.services/images/mini-trello-icon.png) [Відображення карточки товару](https://trello.com/c/jFkO5O64/86-%D0%B2%D1%96%D0%B4%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D1%83)

2021-04-20 19:17 UTC, kharkov-timur commented on components/star-rating/star-rating.tsx
> +  const [hoverRating, setHoverRating] = useState(0);
Другий стейт використовується для відображення наведення на зірки рейтингу

2021-04-22 12:31 UTC, ArtemBozhok requested changes

2021-04-22 12:31 UTC, ArtemBozhok commented on components/modals/cart/products-in-cart-item/product-in-cart-item.tsx
> +
видали комени, я так розмію це ти їх те старий твій код а нижче код із дев після мерджу.
Лишитись повинно то що в дев.

2021-04-22 12:31 UTC, ArtemBozhok commented on components/products/product-item/product-item.tsx
> +
те саме

2021-04-22 12:31 UTC, ArtemBozhok commented on components/modals/cart/products-in-cart-item/product-in-cart-item.tsx
> +
усі ці такі місця передивись

2021-04-22 13:51 UTC, ArtemBozhok approved these changes

2021-04-22 13:52 UTC, merged