Login/registration
wearethefuture-org/shop-auction-front pull request #94
Opened 2021-04-20 11:51 UTC by Kovalova22

2021-04-20 11:57 UTC, Kovalova22 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Налаштувати підтягування даних з google](https://trello.com/c/DeiZLF6L/97-%D0%BD%D0%B0%D0%BB%D0%B0%D1%88%D1%82%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D0%BF%D1%96%D0%B4%D1%82%D1%8F%D0%B3%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%B4%D0%B0%D0%BD%D0%B8%D1%85-%D0%B7-google)

2021-04-21 17:23 UTC, ArtemBozhok requested changes

2021-04-21 17:23 UTC, ArtemBozhok commented on components/forms/auth/register.tsx
> +          scope="https://www.googleapis.com/auth/user.birthday.read https://www.googleapis.com/auth/user.phonenumbers.read"
винеси оці стрінги в масив
стоври окрему функцію яка тобі зробить join через пробіл і заюзай її тут
бо виглядає це не дуже.

2021-04-21 17:23 UTC, ArtemBozhok commented on components/forms/auth/login.tsx
> +        const res = await api.user.googleSignIn(googleUser);
юзай деструктурізацію

const {googleId, email ....} = response.profileObj;


const googleUser = {
          googleId,
          email,
....
        };

2021-04-22 14:05 UTC, ArtemBozhok approved these changes

2021-04-22 14:05 UTC, merged