TASK-98 exit in the mobile version of the site
wearethefuture-org/shop-auction-front pull request #98
Opened 2021-04-20 20:06 UTC by maxim-zabolotny

2021-04-20 20:07 UTC, maxim-zabolotny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Вихід в мобільній версії сайту](https://trello.com/c/MJnZ7dQV/98-%D0%B2%D0%B8%D1%85%D1%96%D0%B4-%D0%B2-%D0%BC%D0%BE%D0%B1%D1%96%D0%BB%D1%8C%D0%BD%D1%96%D0%B9-%D0%B2%D0%B5%D1%80%D1%81%D1%96%D1%97-%D1%81%D0%B0%D0%B9%D1%82%D1%83)

2021-04-22 13:44 UTC, ArtemBozhok requested changes

2021-04-22 13:44 UTC, ArtemBozhok commented on components/SideMenu/account-menu.tsx
> +                [styles['btn-active']]: queryPage === EAccountUrls.comments,
тобі не потрібен тут класнеймз, це ти просто копіпаст зробив.
це кнопка яка не має змінювати свій клас від урла

2021-04-28 12:19 UTC, ArtemBozhok approved these changes

2021-04-28 12:19 UTC, merged